/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Topic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        SuppliersMenu = new javax.swing.JMenu();
        addSupplierMenuItem = new javax.swing.JMenuItem();
        updateDeleteSuppliersMenuItem = new javax.swing.JMenuItem();
        suppliersAllMenuItem = new javax.swing.JMenuItem();
        productMenu = new javax.swing.JMenu();
        addproductMenuItem = new javax.swing.JMenuItem();
        updateDeleteproductMenuItem = new javax.swing.JMenuItem();
        productListMenuItem = new javax.swing.JMenuItem();
        OrdersMenu = new javax.swing.JMenu();
        addOrderMenuItem = new javax.swing.JMenuItem();
        updateDeleteOrderMenuItem = new javax.swing.JMenuItem();
        OrdersListMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - CIMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        Topic.setFont(new java.awt.Font("French Script MT", 1, 55)); // NOI18N
        Topic.setForeground(new java.awt.Color(255, 255, 255));
        Topic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Topic.setText("Crochet Items Management System");

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.JPG"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Topic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(background)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Topic, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 670, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CIMS - Home.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 550));

        SuppliersMenu.setText("Suppliers");

        addSupplierMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        addSupplierMenuItem.setText("Add Supplier");
        addSupplierMenuItem.setToolTipText("");
        addSupplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierMenuItemActionPerformed(evt);
            }
        });
        SuppliersMenu.add(addSupplierMenuItem);

        updateDeleteSuppliersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteSuppliersMenuItem.setText("Update Or Delete Suppliers");
        updateDeleteSuppliersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteSuppliersMenuItemActionPerformed(evt);
            }
        });
        SuppliersMenu.add(updateDeleteSuppliersMenuItem);

        suppliersAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        suppliersAllMenuItem.setText("Suppliers List");
        suppliersAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersAllMenuItemActionPerformed(evt);
            }
        });
        SuppliersMenu.add(suppliersAllMenuItem);

        jMenuBar1.add(SuppliersMenu);

        productMenu.setText("Products");
        productMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuActionPerformed(evt);
            }
        });

        addproductMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addproductMenuItem.setText("Add Product");
        addproductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductMenuItemActionPerformed(evt);
            }
        });
        productMenu.add(addproductMenuItem);

        updateDeleteproductMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteproductMenuItem.setText("Update Or Delete Product");
        updateDeleteproductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteproductMenuItemActionPerformed(evt);
            }
        });
        productMenu.add(updateDeleteproductMenuItem);

        productListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        productListMenuItem.setText("All Products");
        productListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productListMenuItemActionPerformed(evt);
            }
        });
        productMenu.add(productListMenuItem);

        jMenuBar1.add(productMenu);

        OrdersMenu.setText("Orders");
        OrdersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersMenuActionPerformed(evt);
            }
        });

        addOrderMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addOrderMenuItem.setText("Add Order");
        addOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderMenuItemActionPerformed(evt);
            }
        });
        OrdersMenu.add(addOrderMenuItem);

        updateDeleteOrderMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteOrderMenuItem.setText("Update Or Delete Order");
        updateDeleteOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteOrderMenuItemActionPerformed(evt);
            }
        });
        OrdersMenu.add(updateDeleteOrderMenuItem);

        OrdersListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        OrdersListMenuItem.setText("All Order");
        OrdersListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersListMenuItemActionPerformed(evt);
            }
        });
        OrdersMenu.add(OrdersListMenuItem);

        jMenuBar1.add(OrdersMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productMenuActionPerformed

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_backgroundMouseClicked

    private void addproductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddProduct().setVisible(true);
        
    }//GEN-LAST:event_addproductMenuItemActionPerformed

    private void addSupplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddSupplier().setVisible(true);
    }//GEN-LAST:event_addSupplierMenuItemActionPerformed

    private void suppliersAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersAllMenuItemActionPerformed
        // TODO add your handling code here:
        new View.SuppliersList().setVisible(true);
    }//GEN-LAST:event_suppliersAllMenuItemActionPerformed

    private void productListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.ProductsList().setVisible(true);
    }//GEN-LAST:event_productListMenuItemActionPerformed

    private void updateDeleteSuppliersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteSuppliersMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteSuppliers().setVisible(true);
    }//GEN-LAST:event_updateDeleteSuppliersMenuItemActionPerformed

    private void updateDeleteproductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteproductMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteProducts().setVisible(true);
    }//GEN-LAST:event_updateDeleteproductMenuItemActionPerformed

    private void addOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddOrders().setVisible(true);
    }//GEN-LAST:event_addOrderMenuItemActionPerformed

    private void updateDeleteOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteOrderMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteOrder().setVisible(true);
    }//GEN-LAST:event_updateDeleteOrderMenuItemActionPerformed

    private void OrdersListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.OrdersList().setVisible(true);
    }//GEN-LAST:event_OrdersListMenuItemActionPerformed

    private void OrdersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OrdersListMenuItem;
    private javax.swing.JMenu OrdersMenu;
    private javax.swing.JMenu SuppliersMenu;
    private javax.swing.JLabel Topic;
    private javax.swing.JMenuItem addOrderMenuItem;
    private javax.swing.JMenuItem addSupplierMenuItem;
    private javax.swing.JMenuItem addproductMenuItem;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem productListMenuItem;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenuItem suppliersAllMenuItem;
    private javax.swing.JMenuItem updateDeleteOrderMenuItem;
    private javax.swing.JMenuItem updateDeleteSuppliersMenuItem;
    private javax.swing.JMenuItem updateDeleteproductMenuItem;
    // End of variables declaration//GEN-END:variables
}
